version: 2

build:
  os: ubuntu-24.04
  tools:
    python: "3.10"  # pre-install for the py310 environment of pixi
  jobs:
    post_checkout:
      # Download and uncompress binary for the desired version of Git LFS
      - |
        set -e
        LFS_VERSION="3.4.0"
        wget "https://github.com/git-lfs/git-lfs/releases/download/v${LFS_VERSION}/git-lfs-linux-amd64-v${LFS_VERSION}.tar.gz"
        tar xzf "git-lfs-linux-amd64-v${LFS_VERSION}.tar.gz" --strip-components=1 "git-lfs-${LFS_VERSION}/git-lfs"
        rm "git-lfs-linux-amd64-v${LFS_VERSION}.tar.gz"
      # Modify LFS config paths to point where git-lfs binary was downloaded
      - git config filter.lfs.process "$(pwd)/git-lfs filter-process"
      - git config filter.lfs.smudge  "$(pwd)/git-lfs smudge -- %f"
      - git config filter.lfs.clean "$(pwd)/git-lfs clean -- %f"
      # Make LFS available in current repository
      - ./git-lfs install
      # Download content from remote
      - ./git-lfs fetch
      # Make local files to have the real content on them
      - ./git-lfs checkout

    create_environment:
      - asdf plugin add pixi
      - asdf install pixi latest
      - asdf global pixi latest

    build:
      html:
        - pixi run --frozen build-docs html $READTHEDOCS_OUTPUT
