version: 2

# Set the version of Python and other tools you might need
build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_checkout:
      - echo "[RTD] Configure Git LFS"
      - |
        set -e
        # Update version of Git LFS as needed here:
        LFS_VERSION="3.4.0"
        wget "https://github.com/git-lfs/git-lfs/releases/download/v${LFS_VERSION}/git-lfs-linux-amd64-v${LFS_VERSION}.tar.gz"
        tar xzf "git-lfs-linux-amd64-v${LFS_VERSION}.tar.gz" --strip-components=1 "git-lfs-${LFS_VERSION}/git-lfs"
        rm "git-lfs-linux-amd64-v${LFS_VERSION}.tar.gz"
      - |
        set -e
        git_lfs_path="$(pwd)"
        git config filter.lfs.process "$git_lfs_path/git-lfs filter-process"
        git config filter.lfs.smudge  "$git_lfs_path/git-lfs smudge -- %f"
        git config filter.lfs.clean "$git_lfs_path/git-lfs clean -- %f"
      - |
        set -e
        ./git-lfs install
        ./git-lfs fetch
        ./git-lfs checkout

    pre_build:
      # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "jupyter-book config sphinx docs/"
      - "pip install . --no-deps"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

conda:
    environment: docs/environment.yml
