version: 2

# Set the version of Python and other tools you might need
build:
  os: "ubuntu-22.04"
  tools:
    python: "mambaforge-22.9"
  jobs:
    post_checkout:
      # Configure Git LFS
      - echo "[RTD] Configure Git LFS"
      # Download and install latest Git LFS (update version as needed)
      # https://git-lfs.github.com/
      - |
        set -e
        LFS_VERSION="3.4.0"
        wget "https://github.com/git-lfs/git-lfs/releases/download/v${LFS_VERSION}/git-lfs-linux-amd64-v${LFS_VERSION}.tar.gz"
        tar xzf "git-lfs-linux-amd64-v${LFS_VERSION}.tar.gz"
        rm "git-lfs-linux-amd64-v${LFS_VERSION}.tar.gz"

      # Configure Git LFS paths and settings
      - |
        set -e
        git config filter.lfs.process "`pwd`/git-lfs filter-process"
        git config filter.lfs.smudge  "`pwd`/git-lfs smudge -- %f"
        git config filter.lfs.clean "`pwd`/git-lfs clean -- %f"

        # Make LFS available in current repository
        ./git-lfs install

        # Download and checkout LFS content
        ./git-lfs fetch
        ./git-lfs checkout

      # Unshallow repository for auto-versioning
      - echo "[RTD] Unshallow repository for version detection"
      - |
        set -e
        # Fetch version tags
        git fetch origin --no-tags '+refs/tags/v[0-9]*:refs/tags/v[0-9]*' --depth=1

        # Get latest version tag
        latest_tag="$(git tag -l 'v[0-9]*' --sort=-v:refname | head -n1)"
        echo "[RTD] Latest version tag: $latest_tag"

        # Determine current branch
        branch="$(git rev-parse --abbrev-ref HEAD)"
        if [ "$branch" = "HEAD" ]; then
          branch="$(git symbolic-ref --short refs/remotes/origin/HEAD | sed 's@^origin/@@')"
        fi
        echo "[RTD] Current branch: $branch"

        # Unshallow to latest tag
        if [ -n "$latest_tag" ]; then
          git fetch origin "$branch" --update-shallow --shallow-exclude="$latest_tag^"
          echo "[RTD] Repository unshallowed successfully"
        else
          echo "[RTD] Warning: No version tags found, skipping unshallow"
        fi

    pre_build:
      # Generate on-the-fly Sphinx configuration from Jupyter Book's _config.yml
      - "jupyter-book config sphinx docs/"
      - "pip install . --no-deps"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  builder: html
  configuration: docs/conf.py
  fail_on_warning: false

conda:
    environment: docs/environment.yml
