name: geoh5py

channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.7
  - h5py
  - pip:
    - sphinx
    - sphinx_issues
    - sphinx_rtd_theme
    - sphinxcontrib-bibtex
    - nbsphinx
    - nbstripout
    - numpydoc
    - jupyter_client
