{% set name = "geoh5py" %}
{% set version = "0.11.0a1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  # url: https://github.com/MiraGeoscience/{{ name }}/archive/v{{ version }}.tar.gz
  # sha256: 71ef863971355dcaf255c5e1824be5cf091c87940ab930001ab08ca8bfd11441
  path: ../{{ name}}

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.10.0,<3.11
    - poetry-core >=1.0.0
    - setuptools
    - pip
  run:
    - python >=3.10.0,<3.11
    - pydantic >=2.5.2,<3.0.0
    - h5py >=3.2.1,<4.0.0
    - numpy >=1.26.0,<1.27.0
    - pillow >=10.3.0,<10.4.0

test:
  imports:
    - geoh5py
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.mirageoscience.com/mining-industry-software/python-integration/
  summary: 'Python API for geoh5, an open file format for geoscientific data.'
  description: |
    The geoh5py library has been created for the manipulation and storage of a wide range of
    geoscientific data (points, curve, surface, 2D and 3D grids) in GEOH5 file format. Users will
    be able to directly leverage the powerful visualization capabilities of
    (Geoscience ANALYST)<https://mirageoscience.com/mining-industry-software/geoscience-analyst/>
    along with open-source code from the Python ecosystem.
  license: LGPL-3.0-only
  license_file:
    - COPYING
    - COPYING.LESSER
  doc_url: https://mirageoscience-geoh5py.readthedocs-hosted.com/
  dev_url: https://github.com/MiraGeoscience/geoh5py

extra:
  recipe-maintainers:
    - SophieCurinier
    - sebhmg
