schema_version: 1

context:
  name: "geoh5py"
  version: "0.0.0.dev0"  # This will be replaced by the actual version in the build process
  python_min: "3.10"
  module_name: ${{ name|lower|replace("-", "_") }}

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  path: ../${{ name}}

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - python 3.10.*
    - poetry-core >=1.8.0
    - poetry-dynamic-versioning >=1.9, 1.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - h5py >=3.2.1, 3.*
    - numpy >=1.26.0, 1.26.*
    - pillow >=10.3.0, 10.3.*
    - pydantic 2.11.*

tests:
  - python:
      imports:
        - ${{ module_name }}
        - ${{ module_name }}._version
  - script:
      - pytest --ignore=tests/version_test.py
    requirements:
      run:
        - pytest
        - scipy >= 1.14.0, <1.15.dev
    files:
      source:
        - tests/
  - package_contents:
      files:
        - site-packages/${{ module_name }}/_version.py

about:
  summary: Python API for geoh5, an open file format for geoscientific data.
  description: |
    The geoh5py library has been created for the manipulation and storage of a wide range of
    geoscientific data (points, curve, surface, 2D and 3D grids) in GEOH5 file format. Users will
    be able to directly leverage the powerful visualization capabilities of
    (Geoscience ANALYST)<https://mirageoscience.com/mining-industry-software/geoscience-analyst/>
    along with open-source code from the Python ecosystem.
  license: LGPL-3.0-only
  license_file:
    - COPYING
    - COPYING.LESSER
    - docs/THIRD_PARTY_SOFTWARE.rst
  homepage: https://www.mirageoscience.com/mining-industry-software/python-integration/
  repository: https://github.com/MiraGeoscience/geoh5py
  documentation: https://mirageoscience-geoh5py.readthedocs-hosted.com/

extra:
  recipe-maintainers:
    - andrewg-mira
    - sebhmg
