#
# geoh5py documentation build configuration file, created by
# sphinx-quickstart on Tue Sep 16 16:41:10 2014.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# on_rtd is whether we are on readthedocs.org
import os
import sys

from datetime import datetime
from pathlib import Path
from importlib.metadata import version
from packaging.version import Version

sys.path.append(str(Path("_ext").resolve()))
sys.path.append(str(Path().parent.resolve()))

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use pathlib.Path.resolve to make it absolute, like shown here.
# sys.path.insert(0, Path().resolve())

# Configuration file for the Sphinx documentation builder.
#
# For the full list of built-in configuration values, see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Project information -----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#project-information

project = "geoh5py"
author = "Mira Geoscience Ltd."
project_copyright = "%Y, Mira Geoscience Ltd"

# -- General configuration ---------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#general-configuration

# The full version, including alpha/beta/rc tags.
release = version("geoh5py")
# The shorter X.Y.Z version.
version = Version(release).base_version


googleanalytics_id = "G-9EY47HMNZX"

# Autosummary pages will be generated by sphinx-autogen instead of sphinx-build
autosummary_generate = []
autodoc_mock_imports = [
    "h5py",
    "numpy",
]

needs_sphinx = "2.2.1"
extensions = [
    "jupyter_book",
    "myst_nb",
    "numpydoc",
    "nbsphinx",
    "sphinx.ext.autodoc",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.todo",
    "sphinx_book_theme",
    "sphinx_comments",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinx_external_toc",
    "sphinx_issues",
    "sphinx_jupyterbook_latex",
    "sphinx_multitoc_numbering"
    "sphinx_thebe",
    "sphinx_togglebutton",
    "sphinxcontrib.googleanalytics",
]

templates_path = ["_templates"]
exclude_patterns = ['**.ipynb_checkpoints', '.DS_Store', 'Thumbs.db', '_build']
todo_include_todos = True

comments_config = {'hypothesis': False, 'utterances': False}  #??

pygments_style = 'sphinx'
suppress_warnings = ['etoc.toctree']
use_multitoc_numbering = True

# -- Options for auto-doc ----------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html#module-sphinx.ext.autodoc

autodoc_typehints = "signature"
autodoc_typehints_format = "short"
autodoc_type_aliases = {"np.ndarray": "numpy.ndarray", "UUID": "uuid.UUID"}
intersphinx_mapping = {
    # use None to auto‑fetch objects.inv
    'numpy': ['https://numpy.org/doc/1.26/', None],
    'python': ['https://docs.python.org/3/', None],
}

# -- Options for external TOC --------------------------------------------------
external_toc_exclude_missing = False
external_toc_path = '_toc.yml'

# -- Options for MyST-NB -----------------------------------------------------
myst_enable_extensions = [
    "colon_fence", "dollarmath", "linkify", "substitution", "tasklist"
]
myst_url_schemes = ["mailto", "http", "https"]

# -- Options for notebook execution ---------------------------------------------
nb_execution_allow_errors = False
nb_execution_cache_path = ""
nb_execution_excludepatterns = []
nb_execution_in_temp = True
nb_execution_mode = "force"
nb_execution_timeout = 30
nb_output_stderr = "show"

use_jupyterbook_latex = True
latex_engine = "pdflatex"

# -- Options for HTML output -------------------------------------------------
# https://www.sphinx-doc.org/en/master/usage/configuration.html#options-for-html-output

#html_theme = 'sphinx_book_theme'
#html_theme_options = {'search_bar_text': 'Search this book...', 'launch_buttons': {'notebook_interface': 'classic', 'binderhub_url': '', 'jupyterhub_url': '', 'thebe': False, 'colab_url': '', 'deepnote_url': ''}, 'path_to_docs': 'docs', 'repository_url': 'https://github.com/executablebooks/jupyter-book', 'repository_branch': 'main', 'extra_footer': '', 'home_page_in_toc': True, 'announcement': '', 'analytics': {'google_analytics_id': '', 'plausible_analytics_domain': '', 'plausible_analytics_url': 'https://plausible.io/js/script.js'}, 'use_repository_button': True, 'use_edit_page_button': False, 'use_issues_button': True}

html_theme = "alabaster"
html_logo = "images/geoh5py_logo.png"
html_theme_options = {
    "description": f"version {release}",
    "fixed_sidebar": True,
    "logo_name": "Geoh5py",
    "show_relbars": True,
}
html_title = "Geoh5py"

html_static_path = ["_static/custom.css"]

check_meta = False

# Enable numref
numfig = True


def get_copyright_notice():
    return f"Copyright {datetime.now().strftime(project_copyright)}"


rst_epilog = f"""
.. |copyright_notice| replace:: {get_copyright_notice()}.
"""

# -- Edit on Github Extension ---------------------------------------------
edit_on_github_branch = "main"
edit_on_github_project = "mirageoscience/geoh5py"
edit_on_github_directory = "docs"
