name: Dependabot auto-merge

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  call-workflow-dependabot-auto-merge:
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-dependabot-auto-merge.yml@f3b68e8e220bd9d1364e28fab77b4785cef291d9 # v3.13.1
    permissions:
      contents: write
      pull-requests: write
      statuses: write
      checks: read
    with:
      dependabot-groups: mirageo-ci-tools,pre-commit-hooks
      checks-to-skip: 'pre-commit.ci - pr,CodeQL'
