name: pytest on Windows

on:
  pull_request:
    branches:
    - development

jobs:
  pytest:
    name: pytest
    runs-on: windows-latest
    env:
      POETRY_VIRTUALENVS_CREATE: false
      POETRY_VIRTUALENVS_IN_PROJECT: false
      POETRY_VIRTUALENVS_PATH: ~/.virtualenvs
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install Poetry
      run: curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
    - name: Environment
      run: echo ::add-path::$HOME/.poetry/bin
    - name: Get poetry cache directory
      id: poetry-cache
      run: echo "::set-output name=dir::$(poetry config virtualenvs.path)"
    - name: Cache dependencies
      uses: actions/cache@v1
      with:
        path: ${{ steps.poetry-cache.outputs.dir }}
        key: ${{ runner.os }}-poetry-venvs-${{ hashFiles('**/poetry.lock') }}
        restore-keys: ${{ runner.os }}-poetry-venvs-
    - name: Install dependencies
      run: poetry install -vvv
    - name: pytest
      run: poetry run pytest --cov-report=xml --cov=geoh5py --cov-branch --cov-fail-under=80
    - name: Codecov
      if: success()
      uses: codecov/codecov-action@v1.0.6
      with:
        name: GitHub
        token: ${{secrets.CODECOV_UPLOAD_TOKEN}}
