name: Python package

on:
  push:
    branches:
    - development
    - master
  pull_request:
    branches:
    - development
    - master

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      uses: abatilo/actions-poetry@master
      with:
        args: install
    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: Run pre-commit hooks on changes
      if: github.event_name == 'pull_request'      
      run: git diff-tree --no-commit-id --name-only -r $GITHUB_SHA | xargs pre-commit run --files
    - name: Run pre-commit hooks on all files
      if: github.event_name == 'push'
      run: pre-commit run --all-files
    - name: Test with pytest
      uses: abatilo/actions-poetry@master
      with:
        args: >-
          run python -m pytest --cov-report xml:codecov.xml --cov=geoh5io
          --cov-report=html --junit-xml=coverage.xml --cov-branch --cov-fail-under=80
