name: Deploy python package in production

on:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  call-workflow-conda-release:
    name: Publish production Conda package on JFrog Artifactory
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-release_conda_assets.yml@feature/DEVOPS-571
    with:
      virtual-repo-names: '["public-conda-prod"]'
    secrets:
      JFROG_ARTIFACTORY_URL: ${{ secrets.JFROG_ARTIFACTORY_URL }}
      JFROG_ARTIFACTORY_TOKEN: ${{ secrets.JFROG_ARTIFACTORY_TOKEN }}
  call-workflow-pypi-release:
    name: Publish production PyPI package (JFrog Artifactory and PyPI)
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-release_pypi_assets.yml@feature/DEVOPS-571
    with:
      package-name: 'geoh5py'
      virtual-repo-names: '["public-pypi-prod", "pypi"]'
    secrets:
      JFROG_ARTIFACTORY_URL: ${{ secrets.JFROG_ARTIFACTORY_URL }}
      JFROG_ARTIFACTORY_TOKEN: ${{ secrets.JFROG_ARTIFACTORY_TOKEN }}
      PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
