name: geoh5io Python package

on:
  push:
    branches:
    - development
    - master
  pull_request:
    branches:
    - development
env:
  python_version: 3.7

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python $python_version
      uses: actions/setup-python@v1
      with:
        python-version: $python_version
    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: Git show refs
      run: git show-ref
    - name: Run pre-commit hooks on modified files
      if: github.event_name == 'pull_request'
      run: >-
        git diff --name-only refs/remotes/origin/development... |
        xargs pre-commit run --config .pre-commit-ci-config.yaml --files
    - name: Run pre-commit hooks on all files
      if: github.event_name == 'push'
      run: pre-commit run --config .pre-commit-ci-config.yaml --all-files

  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python $python_version
      uses: actions/setup-python@v1
      with:
        python-version: $python_version
    - name: Environment
      run: echo ::add-path::$HOME/.poetry/bin
    - name: Install
      run: |
        curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        poetry install
    - name: Run pylint on modified files
      if: github.event_name == 'pull_request'
      run: >-
        poetry run pylint -j0 $(
        git diff --name-only refs/remotes/origin/development... | grep -E '^geoh5io/.*\.py$'
        || echo 'geoh5io/__init__.py'
        )
    - name: Run pylint on all files
      if: github.event_name == 'push'
      run: poetry run pylint -j0 geoh5io

  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{env.python_version}}
      uses: actions/setup-python@v1
      with:
        python-version: ${{env.python_version}}
    - name: Environment
      run: echo ::add-path::$HOME/.poetry/bin
    - name: Install
      run: |
        curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        poetry install
    - name: Run pytest
      run: poetry run pytest --cov-report=xml --cov=geoh5io --cov-branch --cov-fail-under=80
    - name: Upload coverage to Codecov
      if: success()
      run: >-
        bash <(curl -s https://codecov.io/bash) -t ${{secrets.CODECOV_UPLOAD_TOKEN}} -n GitHub
