name: geoh5io Python package

on:
  push:
    branches:
    - development
    - master
  pull_request:
    branches:
    - development
    - master

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: Run pre-commit hooks on changes
      if: github.event_name == 'pull_request'
      run: >-
        git diff-tree --no-commit-id --name-only -r $GITHUB_SHA | xargs pre-commit
        run --config .pre-commit-ci-config.yaml --files
    - name: Run pre-commit hooks on all files
      if: github.event_name == 'push'
      run: pre-commit run --config .pre-commit-ci-config.yaml --all-files

  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      uses: abatilo/actions-poetry@master
      with:
        args: install
    - name: Run pylint
      uses: abatilo/actions-poetry@master
      with:
        args: run python -m pylint -j0 geoh5io

  pytest:
    name: pytest
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Install
      uses: abatilo/actions-poetry@master
      with:
        args: install
    - name: Run pytest
      uses: abatilo/actions-poetry@master
      with:
        args: >-
          run python -m pytest --cov-report xml:codecov.xml --cov=geoh5io
          --cov-report=html --junit-xml=coverage.xml --cov-branch --cov-fail-under=80
    - name: Upload coverage to Codecov
      if: github.ref == 'development' || github.ref == 'master'
      uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_UPLOAD_TOKEN}}
        file: ./codecov.xml
        flags: pytest
