name: Deploy python package in production

on:
  release:
    types: [published] # Trigger for draft release

jobs:
  call-workflow-publish:
    name: Publish production package on JFrog Artifactory
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-python-publish_package.yml@main
    with:
      package-managers: '["conda", "poetry"]'
      package-name: 'geoh5py'
      version-tag: ${{ github.ref_name }}
      python-version: '3.10'
      repo-names: '["public-conda-prod-local", "public-pypi-prod-local"]'
    secrets:
      JFROG_ARTIFACTORY_URL: ${{ secrets.JFROG_ARTIFACTORY_URL }}
      JFROG_ARTIFACTORY_TOKEN: ${{ secrets.JFROG_ARTIFACTORY_TOKEN }}
