name: Security Scan

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**
  push:
    branches:
      - develop
      - main
      - release/**
      - feature/**
      - hotfix/**

permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  call-workflow-zizmor-advanced-security:
    name: Zizmor analysis (advanced security)
    if: ${{ github.event_name != 'pull_request' }}
    permissions:
      security-events: write
      contents: read
      actions: read
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-zizmor-advanced-security.yml@f3b68e8e220bd9d1364e28fab77b4785cef291d9 # v3.13.1

  call-workflow-zizmor-annotate:
    name: Zizmor analysis (annotate)
    if: ${{ github.event_name == 'pull_request' }}
    permissions:
      checks: write
      contents: read
      actions: read
    uses: MiraGeoscience/CI-tools/.github/workflows/reusable-zizmor-annotate.yml@f3b68e8e220bd9d1364e28fab77b4785cef291d9 # v3.13.1
