name: static analysis

on:
  push:
    branches:
    - development
    - master
  pull_request:
    branches:
    - development
    - master

jobs:
  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pre-commit
      run: |
        python -m pip install --upgrade pip
        pip install pre-commit
    - name: Git show refs
      run: git show-ref
    - name: Run pre-commit hooks on modified files
      if: github.event_name == 'pull_request'
      run: >-
        git diff --name-only refs/remotes/origin/${{github.base_ref}}... |
        xargs pre-commit run --config .pre-commit-ci-config.yaml --files
    - name: Run pre-commit hooks on all files
      if: github.event_name == 'push'
      run: pre-commit run --config .pre-commit-ci-config.yaml --all-files

  pylint:
    name: pylint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Environment
      run: echo ::add-path::$HOME/.poetry/bin
    - name: Install
      run: |
        curl -sSL https://raw.githubusercontent.com/sdispater/poetry/master/get-poetry.py | python
        poetry install
    - name: Run pylint on modified files
      if: github.event_name == 'pull_request'
      run: >-
        poetry run pylint -j0 $(
        git diff --diff-filter=AM --name-only refs/remotes/origin/${{github.base_ref}}... | grep -E '^(geoh5py|tests)/.*\.py$'
        || echo 'geoh5py/__init__.py'
        )
    - name: Run pylint on all files
      if: github.event_name == 'push'
      run: poetry run pylint -j0 geoh5py tests
